module.exports = {
    moduleFileExtensions: ["js", "json", "ts"],
    rootDir: ".",
    testRegex: ".*\\.spec\\.ts$",
    transform: {
        "^.+\\.(t|j)s$": "ts-jest",
    },
    collectCoverageFrom: ["apps/**/*.(t|j)s", "libs/**/*.(t|j)s"],
    coverageDirectory: "./coverage",
    testEnvironment: "node",
    roots: ["<rootDir>/apps/", "<rootDir>/libs/"],
    moduleNameMapper: {
        "^@app/campaign/(.*)$": "<rootDir>/apps/campaign/src/$1",
        "^@app/auth/(.*)$": "<rootDir>/apps/auth/src/$1",
        "^@app/user/(.*)$": "<rootDir>/apps/user/src/$1",
        "^@libs/aws-cognito$": "<rootDir>/libs/aws-cognito/index.ts",
        "^@libs/aws-cognito/(.*)$": "<rootDir>/libs/aws-cognito/$1",
        "^@libs/observability$": "<rootDir>/libs/observability/index.ts",
        "^@libs/observability/(.*)$": "<rootDir>/libs/observability/$1",
        "^@libs/redis$": "<rootDir>/libs/redis/index.ts",
        "^@libs/redis/(.*)$": "<rootDir>/libs/redis/$1",
        "^@libs/auth$": "<rootDir>/libs/auth/index.ts",
        "^@libs/auth/(.*)$": "<rootDir>/libs/auth/$1",
        "^@libs/aws-sqs$": "<rootDir>/libs/aws-sqs/index.ts",
        "^@libs/aws-sqs/(.*)$": "<rootDir>/libs/aws-sqs/$1",
        "^@libs/aws-opensearch$": "<rootDir>/libs/aws-opensearch/index.ts",
        "^@libs/aws-opensearch/(.*)$": "<rootDir>/libs/aws-opensearch/$1",
        "^@libs/payos$": "<rootDir>/libs/payos/index.ts",
        "^@libs/payos/(.*)$": "<rootDir>/libs/payos/$1",
        "^@libs/grpc$": "<rootDir>/libs/grpc/index.ts",
        "^@libs/grpc/(.*)$": "<rootDir>/libs/grpc/$1",
        "^@libs/s3-storage$": "<rootDir>/libs/s3-storage/index.ts",
        "^@libs/s3-storage/(.*)$": "<rootDir>/libs/s3-storage/$1",
        "^@libs/graphql/(.*)$": "<rootDir>/libs/graphql/$1",
        "^@libs/env$": "<rootDir>/libs/env/index.ts",
        "^@libs/env/(.*)$": "<rootDir>/libs/env/$1",
        "^@libs/databases$": "<rootDir>/libs/databases/index.ts",
        "^@libs/databases/(.*)$": "<rootDir>/libs/databases/$1",
        "^@libs/common$": "<rootDir>/libs/common/index.ts",
        "^@libs/common/(.*)$": "<rootDir>/libs/common/$1",
        "^@libs/exceptions$": "<rootDir>/libs/exceptions/index.ts",
        "^@libs/exceptions/(.*)$": "<rootDir>/libs/exceptions/$1",
        "^@libs/validation$": "<rootDir>/libs/validation/index.ts",
        "^@libs/validation/(.*)$": "<rootDir>/libs/validation/$1",
        "^libs/aws-cognito$": "<rootDir>/libs/aws-cognito/index.ts",
        "^libs/aws-cognito/(.*)$": "<rootDir>/libs/aws-cognito/$1",
        "^libs/common$": "<rootDir>/libs/common/index.ts",
        "^libs/common/(.*)$": "<rootDir>/libs/common/$1",
        "^libs/databases$": "<rootDir>/libs/databases/index.ts",
        "^libs/databases/(.*)$": "<rootDir>/libs/databases/$1",
        "^libs/env$": "<rootDir>/libs/env/index.ts",
        "^libs/env/(.*)$": "<rootDir>/libs/env/$1",
        "^libs/exceptions$": "<rootDir>/libs/exceptions/index.ts",
        "^libs/exceptions/(.*)$": "<rootDir>/libs/exceptions/$1",
        "^libs/graphql/(.*)$": "<rootDir>/libs/graphql/$1",
        "^libs/s3-storage$": "<rootDir>/libs/s3-storage/index.ts",
        "^libs/s3-storage/(.*)$": "<rootDir>/libs/s3-storage/$1",
        "^libs/observability$": "<rootDir>/libs/observability/index.ts",
        "^libs/observability/(.*)$": "<rootDir>/libs/observability/$1",
        "^libs/grpc$": "<rootDir>/libs/grpc/index.ts",
        "^libs/grpc/(.*)$": "<rootDir>/libs/grpc/$1",
        "^libs/validation$": "<rootDir>/libs/validation/index.ts",
        "^libs/validation/(.*)$": "<rootDir>/libs/validation/$1",
    },
}
