name: foodfund-microservices
region: sgp1
envs:
  # App-level envs (chia sẻ cho tất cả services)
  - key: NODE_ENV
    value: "development"
    scope: RUN_TIME
    type: GENERAL
  - key: SENTRY_DSN
    value: ${SENTRY_DSN}
    scope: RUN_TIME
    type: SECRET
  - key: SENTRY_ENVIRONMENT
    value: ${SENTRY_ENVIRONMENT}
    scope: RUN_TIME
    type: SECRET
  - key: SENTRY_RELEASE
    value: ${SENTRY_RELEASE}
    scope: RUN_TIME
    type: SECRET  

services:
  # Auth Service
  - name: auth-service
    image:
      registry_type: DOCKER_HUB
      registry: "ttrece"
      repository: "foodfund-auth"
      tag: develop
    http_port: 8002
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: USERS_DATABASE_URL
        scope: RUN_TIME
        type: SECRET
        value: ${USERS_DATABASE_URL}
      - key: AWS_REGION
        scope: RUN_TIME
        type: SECRET
        value: ${AWS_REGION}
      - key: AWS_COGNITO_USER_POOL_ID
        scope: RUN_TIME
        type: SECRET
        value: ${AWS_COGNITO_USER_POOL_ID}
      - key: AWS_COGNITO_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
        value: ${AWS_COGNITO_CLIENT_ID}
      - key: AWS_ACCESS_KEY_ID
        scope: RUN_TIME
        type: SECRET
        value: ${AWS_ACCESS_KEY_ID}
      - key: AWS_SECRET_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
        value: ${AWS_SECRET_ACCESS_KEY}
      - key: AWS_COGNITO_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
        value: ${AWS_COGNITO_CLIENT_SECRET}


  # User Service
  - name: user-service
    image:
      registry_type: DOCKER_HUB
      registry: "ttrece"
      repository: "foodfund-user"
      tag: develop
    http_port: 8003
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: USERS_DATABASE_URL
        scope: RUN_TIME
        type: SECRET
        value: ${USERS_DATABASE_URL}

  # GraphQL Gateway
  - name: graphql-gateway
    image:
      registry_type: DOCKER_HUB
      registry: "ttrece"
      repository: "foodfund-graphql-gateway"
      tag: develop
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: AUTH_HOST
        value: "auth-service"  # Bindable variable
        scope: RUN_TIME
        type: GENERAL
      - key: AUTH_PORT
        value: "8002"
        scope: RUN_TIME
        type: GENERAL
      - key: USERS_SUBGRAPH_HOST
        value: "user-service"  # Bindable variable
        scope: RUN_TIME
        type: GENERAL
      - key: USERS_SUBGRAPH_PORT
        value: "8003"
        scope: RUN_TIME
        type: GENERAL

ingress:
  rules:
    - match:
        path:
          prefix: /
      component:
        name: graphql-gateway
    - match:
        path:
          prefix: /auth
      component:
        name: auth-service