name: foodfund-microservices
region: sgp1
services:
  - name: auth
    environment_slug: node-js
    instance_size_slug: basic-xxs
    instance_count: 1
    image:
      registry_type: DOCKER_HUB
      repository: ttrece/foodfund-auth  
      tag: develop
    http_port: 8002


  - name: user
    environment_slug: node-js
    instance_size_slug: basic-xxs
    instance_count: 1
    image:
      registry_type: DOCKER_HUB
      repository: ttrece/foodfund-user  
      tag: develop
    http_port: 8003

  - name: gateway
    environment_slug: node-js
    instance_size_slug: basic-xxs
    instance_count: 1
    image:
      registry_type: DOCKER_HUB
      repository: ttrece/foodfund-graphql-gateway  
      tag: develop
    http_port: 8000
    routes:
      - path: /
