name: foodfund-microservices
region: sgp

services:
  # Auth Service
  - name: auth-service
    image:
      registry_type: DOCKER_HUB
      repository: ttrece/foodfund-auth
      tag: develop
    http_port: 8002
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: USERS_DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: AWS_REGION
        scope: RUN_TIME
        type: SECRET
      - key: AWS_ACCESS_KEY_ID
        scope: RUN_TIME
        type: SECRET
      - key: AWS_SECRET_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
      - key: AWS_COGNITO_USER_POOL_ID
        scope: RUN_TIME
        type: SECRET
      - key: AWS_COGNITO_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: AWS_COGNITO_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET

  # User Service
  - name: user-service
    image:
      registry_type: DOCKER_HUB
      repository: ttrece/foodfund-user
      tag: develop
    http_port: 8003
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: USERS_DATABASE_URL
        scope: RUN_TIME
        type: SECRET

  # GraphQL Gateway
  - name: graphql-gateway
    image:
      registry_type: DOCKER_HUB
      repository: ttrece/foodfund-graphql-gateway
      tag: develop
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: AUTH_HOST
        scope: RUN_TIME
        value: "auth-service"
      - key: AUTH_PORT
        scope: RUN_TIME
        value: "8002"
      - key: USERS_SUBGRAPH_HOST
        scope: RUN_TIME
        value: "user-service"
      - key: USERS_SUBGRAPH_PORT
        scope: RUN_TIME
        value: "8003"

ingress:
  rules:
    - match:
        path:
          prefix: /
      component:
        name: graphql-gateway
    - match:
        path:
          prefix: /auth
      component:
        name: auth-service
